### ISSUE TITLE
Support EAP IntelliJ versions

### ISSUE THREAD

**Issue by tmccarthy** [cashapp/hermit-ij-plugin#36]
Not sure exactly what's involved to achieve this but I believe the way that [upgrade-major-versions.sh](https://github.com/cashapp/hermit-ij-plugin/blob/a1f593ee69504f82614db2089486ede5566a3563/upgrade-major-versions.sh#L10) currently works means that early access versions of IntelliJ are never supported (since they will always have a newer version number than the current `release` version).

I think this means that you can't use EAP releases of IntelliJ along with the hermit plugin.

**Comment by tmccarthy** [comment]
Obviously this isn't critical, feel free to close if it's not something that's worth supporting. I don't have space to try to make this change myself but I might have a go if/when I've got some time.

**Comment by jvmakine** [comment]
To support this, we need to figure out how to map the build code for an EAP build from [the build list](https://data.services.jetbrains.com/products) to the correct maven snapshot
See how EAP artifacts are defined at https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html#example-artifact-specification
