### ISSUE TITLE
Rely on Trust Project dialog

### ISSUE THREAD

**Issue by jvmakine** [cashapp/hermit-ij-plugin#37]
- We should automatically enable Hermit when the IJ project has been opened in trusted mode.
- Hermit should always be disabled in the preview mode
- There should be a way to manually disable Hermit if the user wants to.

See https://www.jetbrains.com/help/idea/project-security.html for an explanation on how the IJ Project security modes work

**Comment by OmarTawfik** [comment]
This work involves:

- [ ] replacing the custom hermit popup with the native IJ import.
- [ ] updating compatibility tests to support the minimum version of the API + the current maximum.
  - `build.gradle` links to a a JSON list to map human to machine versions.

Found the API `com.intellij.ide.impl.TrustedProjects.isTrusted()` which is marked as experimental. Unfortunately, they didn't expose the API publicly yet (although they mention it in the docs). I reached out to them to ask, and [I got this response](https://youtrack.jetbrains.com/issue/IJSDK-1367):

> We're currently discussing the proper API for this purpose. I'll provide that one soon and will backport to 2022.1.X (and maybe 2021.3.X if there will be a bugfix update). If you're short on time, you can use Project.isTrusted() for the time being, and later migrate to the new API.

I don't think we should hack around private APIs, and we should wait for one to be officially provided first before using it here.
